# -*- coding: utf-8 -*-
"""Guess_It.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yyLFUfI07OMD2WmLZLRhqsJS957AQG_B
"""

#Day 01 of 100 Days of Python : Project 01 - Mini Game
import random

number=random.randint(1,10)
attempts=3
print("I'm thinking of a number between 1 to 10")
while attempts > 0:
  guess = int(input("Take a Guess: "))
  if guess==number:
    print("Congratulations! You guessed it")
    break
  elif guess<number:
    print("Try a greater number!!")
  elif guess>number:
    print("Try a lower number!!")
  attempts -= 1

if attempts==0:
  print("Sorry, you've run out of attempts, The number was: ",number)

