# -*- coding: utf-8 -*-
"""Day04_NumberComparision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RV5jB3Xlvks9cHa6MZb0DiTJBecknc9V
"""

#Day04 - Number Comparision

#Step 01- User input
num1 = float(input("Enter First Number: "))
num2 = float(input("Enter Second Number: "))

#Step 02- Comparision
print("\n--- Comparison Result ---")
if num1 > num2:
    print(f"{num1} is greater than {num2}.")
elif num1 < num2:
    print(f"{num1} is less than {num2}.")
else:
    print(f"Both numbers are equal.")

#Check for Zero
if num1== 0 or num2 == 0:
  print("\nAt least one number in Zero.")
else:
  print("\nNo number is Zero.")

