# -*- coding: utf-8 -*-
"""Day3-SimpleCalculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S0ZL5-RCZJkMLldfx7N2gbPRIVOMTRVD
"""

#Day03 - Simple Calculator

#Step 01 - User Input
num1=float(input("Enter first number: "))
num2=float(input("Enter second number: "))

#Perform Operations
add = num1 + num2
sub = num1 - num2
prod = num1 * num2
div = num1/num2 if num2 != 0 else "Cannot Divide by Zero"

#Display Results
print("\n--- Results ---")
print(f"Addition : {num1} + {num2} = {add}")
print(f"Subtraction : {num1} - {num2} = {sub}")
print(f"Product : {num1} * {num2} = {prod}")
print(f"Division : {num1} / {num2} = {div}")

4

