# -*- coding: utf-8 -*-
"""Day06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K2gTsh0_4ynXt65BWkk49i26kz2I3-2H
"""

#Day 06 - Basic Math Quiz

#Step 01 - Question function
import random

def gen_question():
    num1 = random.randint(1, 10)
    num2 = random.randint(1, 10)
    oper = random.choice(['+', '-', '*'])
    if oper == '+':
        answer = num1 + num2
    elif oper == '-':
        answer = num1 - num2
    else:
        answer = num1 * num2

    return f"{num1} {oper} {num2}",answer

#Step 02 - Main Loop
def math_quiz():
  score=0
  rounds=5

  print("\n --- Welcome to the Math Quiz! ---")
  print("You wil be presented with problems and you are expected to answer correctly.")

  for i in range(rounds):
    question,correct_answer=gen_question()
    print(f"\nQuestion {i+1}: {question}")
    user_answer=int(input("Your answer: "))
    if user_answer==correct_answer:
      print("Correct!")
      score+=1
    else:
      print(f"Wrong! The correct answer is {correct_answer}.")

  print("\n --- Game Over! ---")
  print(f"Your Final Score : {score}/{rounds}")
  if score == rounds:
    print("\nYou're a Math Genius!!")
  elif score >= rounds//2:
    print("\nGood Job! You did well")
  else:
    print("\nKeep Practicing, you can do better next time.")

#Step 03 - Run the game
math_quiz()

11