# -*- coding: utf-8 -*-
"""Day5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y-L_L8POi_oEvobTlqbRYxkGF-h8y0W3
"""

#Day 05 - Countdown Timer
import time

#Step 01 - User inpput
count=int(input("Enter the number to start the countdown from: "))

#Step 02 - Loop
print("\n --- Countdown Begins ---")
while count>0:
  print(count)
  time.sleep(1)
  count -= 1

#Step 03 - Display
print("\n --- Countdown Ended ---")

